### PR TITLE
Add ZenHub workflow to engineering guidelines

### PR DESCRIPTION
**Pull request by rhuss**
Add some section to clarify our zenhub workflow

### CODE REVIEW

**Comment by TovaCohen** [comment]
I'm wondering how the creation of user doc fits into this workflow. For example, suppose there is an epic for somehow providing three sample APIs for new integrators to use to implement the three-API sample integration in PR1.  Some user doc is required to explain how to connect with these APIs. Would the epic have a task for creating the user doc? Who would create this task?

**Comment by rhuss** [comment]
The Epic should and can have all tasks connected which is related to this Epic. There might be epics which are not relevant for user documentations (like refactorings), but if one is required I suggest to create an issue in syndesis-documentation which is connected to the relevant Epic. This task is worked on as any other task. 

The task would be created probably by the one who created the Epic (because he's the stakeholder for the feature), but everybody is free to attach such a task to the Epic.

I agree, that this should be a question for the Epic author, whether the epic requires end user documentation or not.

@TovaCohen does this somewhat answer your question ?

**Comment by rhuss** [comment]
It might make sense to allow to connect a PR directly to the Epic, if the corresponding issue would be only a placeholder for the PR (because the epic or the design proposal already contains enough information for working on it). This would reduce a bit the issue inflation that I'm afraid of.

Thoughts ?

**Comment by zregvart** [comment]
> It might make sense to allow to connect a PR directly to the Epic, if the corresponding issue would be only a placeholder for the PR (because the epic or the design proposal already contains enough information for working on it). This would reduce a bit the issue inflation that I'm afraid of.

yeah, I at least create issues with the same text as in the pull request description, so I think it will help to deduplicate, and linking works much the same way anyways

**Comment by rhuss** [comment]
ok, I just update the 'rules' a bit reflecting that a PR can be linked directly to the Epic.

**Comment by rhuss** [comment]
@syndesisio/all If there are no objection I'd like to merge this process update as our guidelines.

**Comment by jimmidyson** [comment]
:100:

**Pull request merged**
