### PR TITLE
Data Mapper section added

### PR DESCRIPTION
**Pull request by Delawen**
Moving to website and minor improvements to existing DataMapper docs

### CODE REVIEW

**Comment by Delawen** [comment]
Original was https://github.com/syndesisio/syndesis/blob/master/app/server/docs/design/datamapper.md

**Comment by Delawen** [comment]
It's not exactly a clone, I changed small bits. I can change it more to use different wording.

**Comment by squakez** [comment]
Yeah, don't take me wrong, I was talking from an anti-plagiarism software point of view. Even a single sentence of 4-5 words is considered as a clone.

I do appreciate the effort you're doing, just giving an advice on how that is perceived from SEO perspective. If you want to have an idea you can either use copyscape or other similar tools, though I think none is free. The strategy I use is to randomly select some sentence of the document and use google search by quoting that sentence. If there is some result, than it will considered almost certainly as a clone.

Rewriting is a hard thing to do, I know.

**Comment by Delawen** [comment]
Then cutting it short, changing texts and linking to https://github.com/syndesisio/syndesis/blob/master/app/server/docs/design/datamapper.md

**Comment by squakez** [comment]
Until we do not rewrite the content from scratch, it's the safest way to proceed.

**Pull request merged**
