### PR TITLE
doc: Corrected some format glitches in doc for developing connectors

### PR DESCRIPTION
**Pull request by TovaCohen**
Added some line breaks. 
Moved an image so it (hopefully) appears in the doc for developing connectors.

### CODE REVIEW

**Comment by kahboom** [comment]
Hey @TovaCohen -- you either need to rename the image path from `images/mongodb.png` to `docs/images/mongodb.png` OR (preferably, to stay consistent with the other images), keep this image path change but also move the actual image from `docs/images/mongodb.png` to `static/images/mongodb.png`.

**Comment by TovaCohen** [comment]
Hi @kahboom  - Thanks for looking at this. 
I thought I did move the image to static/images/mongodb.png. This is the last diff in the PR: 

` content/docs/images/mongodb.png → static/images/mongodb.png 
File renamed without changes. `

So I must be missing something. I'm sorry. I don't know what to do.

**Comment by kahboom** [comment]
Ohh so sorry about that, I missed it! 👍

**Comment by TovaCohen** [comment]
Phew! No problem!
And the image is showing up correctly on the site. A little big, but it's there. 
Thanks Rachel!

**Pull request merged**
